# SPDX-License-Identifier: GPL-2.0
dtb-y += exynos9610.dtb
dtbo-y += exynos9610-a50_ltn_dtv_02.dtbo
dtbo-y += exynos9610-a50_ltn_dtv_03.dtbo
dtbo-y += exynos9610-a50_ltn_dtv_04.dtbo
dtbo-y += exynos9610-a50_ltn_dtv_06.dtbo

always            := $(dtb-y) $(dtbo-y)
clean-files       := *.dtb*
